FROM node:20-alpine
WORKDIR /app
COPY package.json pnpm-workspace.yaml tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
RUN npm install -g pnpm
RUN pnpm install
EXPOSE 5173
CMD ["pnpm", "--filter", "cueltc-web", "dev"]
